# Generated by Django 2.2.1 on 2019-05-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_article_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',)},
        ),
    ]
