# Generated by Django 2.2.1 on 2019-05-20 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0008_auto_20190511_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='collect_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collect_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
