# Generated by Django 2.2.1 on 2019-05-20 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0009_article_collect_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='collect_user',
        ),
        migrations.AddField(
            model_name='article',
            name='collect_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='collect_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
