# Generated by Django 2.2.1 on 2019-05-20 03:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20190520_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='collect_user',
            field=models.ManyToManyField(blank=True, related_name='collect_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
