# Generated by Django 2.2.1 on 2019-05-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_remove_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
