# Generated by Django 2.2.1 on 2019-05-20 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0004_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='collect_user',
            field=models.ManyToManyField(blank=True, related_name='collect_user_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
